from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator


class DashboardQueryNode(BaseModel):
    """One safe, declarative backend operation generated by ChatGPT."""

    model_config = ConfigDict(extra="forbid")

    id: str = Field(min_length=1, max_length=80, pattern=r"^[A-Za-z0-9_.-]+$")
    connector: Literal["meta", "ga4", "clarity", "transform"]
    operation: str = Field(min_length=1, max_length=80)
    params: dict[str, Any] = Field(default_factory=dict)
    depends_on: list[str] = Field(default_factory=list)
    required_inputs: list[str] = Field(default_factory=list)
    run_when: Literal["on_open", "on_change", "manual", "always"] = "always"
    optional: bool = False
    cache_ttl_seconds: int = Field(default=60, ge=0, le=86400)


class DashboardQueryPlan(BaseModel):
    """A reusable backend plan for any dashboard section or filter."""

    model_config = ConfigDict(extra="forbid")

    id: str = Field(min_length=1, max_length=100, pattern=r"^[A-Za-z0-9_.-]+$")
    title: str | None = None
    description: str | None = None
    nodes: list[DashboardQueryNode] = Field(min_length=1, max_length=50)
    output: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="after")
    def validate_graph(self):
        ids = [node.id for node in self.nodes]
        if len(ids) != len(set(ids)):
            raise ValueError("Query node IDs must be unique.")
        known = set(ids)
        for node in self.nodes:
            missing = [item for item in node.depends_on if item not in known]
            if missing:
                raise ValueError(f"Node {node.id} depends on unknown nodes: {missing}")
            if node.id in node.depends_on:
                raise ValueError(f"Node {node.id} cannot depend on itself.")
        return self


class DashboardPlanValidateRequest(BaseModel):
    plan: DashboardQueryPlan


class DashboardPlanPreviewRequest(BaseModel):
    plan: DashboardQueryPlan
    inputs: dict[str, Any] = Field(default_factory=dict)
    trigger: Literal["on_open", "on_change", "manual", "always"] = "manual"


class DashboardSectionPublishRequest(BaseModel):
    dashboard_id: str
    section_id: str = Field(min_length=1, max_length=80, pattern=r"^[A-Za-z0-9_.-]+$")
    title: str
    query_plan: DashboardQueryPlan
    presentation: dict[str, Any] = Field(default_factory=dict)
    confirmation_token: str = Field(min_length=16)


class DashboardSavedQueryExecuteRequest(BaseModel):
    inputs: dict[str, Any] = Field(default_factory=dict)
    trigger: Literal["on_open", "on_change", "manual", "always"] = "manual"


class DashboardRuntimeWorkflowRequest(BaseModel):
    action: Literal["capabilities", "validate", "preview", "execute", "publish_section"]
    plan: DashboardQueryPlan | None = None
    inputs: dict[str, Any] = Field(default_factory=dict)
    trigger: Literal["on_open", "on_change", "manual", "always"] = "manual"
    dashboard_id: str | None = None
    section_id: str | None = None
    title: str | None = None
    presentation: dict[str, Any] = Field(default_factory=dict)
    confirmation_token: str | None = None
